/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.glavna;

import domen.Zaposleni;
import forme.autor.FIzmenaAutora;
import forme.autor.FObrisiAutora;
import forme.autor.FUnosAutora;
import forme.autor.FrmIzmenaAutora;
import forme.delo.FormaObrisiDelo;
import forme.delo.FormaUnosDela;
import forme.delo.FrmIzmenaDela;
import forme.delo.FrmObrisiDelo;

import forme.klijent.FIzmenaKlijenta;
import forme.klijent.FObrisiKlijenta;
import forme.klijent.FUnosKlijenta;
import forme.narudzbenica.FormaUnosNarudzbenice;
import forme.narudzbenica.FrmNarudzbenica;
import forme.narudzbenica.FrnObrisiNarudzbenicu;


/**
 *
 * @author miljan
 */
public class GlavnaForma extends javax.swing.JFrame {
Zaposleni korisnik;
    /**
     * Creates new form GlavnaForma
     */
   

    public GlavnaForma(Zaposleni korisnik) {
         initComponents();
         this.korisnik=korisnik;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiUnosAutora = new javax.swing.JMenuItem();
        jmiIzmenaAutora = new javax.swing.JMenuItem();
        jmiObrisiAutora = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiUnosKlijenta = new javax.swing.JMenuItem();
        jmiIzmenaKlijenta = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiUnosDela = new javax.swing.JMenuItem();
        jmiIzmenaDela = new javax.swing.JMenuItem();
        jmiObrisi = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiUnosNarudzbenice = new javax.swing.JMenuItem();
        jmiObrisiNarudbenicu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Autor");

        jmiUnosAutora.setText("Unos autora");
        jmiUnosAutora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosAutoraActionPerformed(evt);
            }
        });
        jMenu1.add(jmiUnosAutora);

        jmiIzmenaAutora.setText("Izmena autora");
        jmiIzmenaAutora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzmenaAutoraActionPerformed(evt);
            }
        });
        jMenu1.add(jmiIzmenaAutora);

        jmiObrisiAutora.setText("Obrisi autora");
        jmiObrisiAutora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiObrisiAutoraActionPerformed(evt);
            }
        });
        jMenu1.add(jmiObrisiAutora);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Klijent");

        jmiUnosKlijenta.setText("Unos klijenta");
        jmiUnosKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosKlijentaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiUnosKlijenta);

        jmiIzmenaKlijenta.setText("Izmena klijenta");
        jmiIzmenaKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzmenaKlijentaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiIzmenaKlijenta);

        jMenuItem2.setText("Obrisi klijenta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Delo");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jmiUnosDela.setText("Unos dela");
        jmiUnosDela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosDelaActionPerformed(evt);
            }
        });
        jMenu3.add(jmiUnosDela);

        jmiIzmenaDela.setText("Izmena dela");
        jmiIzmenaDela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzmenaDelaActionPerformed(evt);
            }
        });
        jMenu3.add(jmiIzmenaDela);

        jmiObrisi.setText("Obrisi delo");
        jmiObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiObrisiActionPerformed(evt);
            }
        });
        jMenu3.add(jmiObrisi);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Narudzbenica");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jmiUnosNarudzbenice.setText("Unos narudzbenice");
        jmiUnosNarudzbenice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosNarudzbeniceActionPerformed(evt);
            }
        });
        jMenu4.add(jmiUnosNarudzbenice);

        jmiObrisiNarudbenicu.setText("Obrisi narudzbenicu");
        jmiObrisiNarudbenicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiObrisiNarudbenicuActionPerformed(evt);
            }
        });
        jMenu4.add(jmiObrisiNarudbenicu);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUnosKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosKlijentaActionPerformed
        FUnosKlijenta forma=new FUnosKlijenta(this, true);
        forma.setVisible(true);
    }//GEN-LAST:event_jmiUnosKlijentaActionPerformed

    private void jmiIzmenaKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzmenaKlijentaActionPerformed
        FIzmenaKlijenta forma=new FIzmenaKlijenta(this, true);
        forma.setVisible(true);
    }//GEN-LAST:event_jmiIzmenaKlijentaActionPerformed

    private void jmiObrisiAutoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiObrisiAutoraActionPerformed
        FObrisiAutora forma=new FObrisiAutora(this, true);
        forma.setVisible(true);
    }//GEN-LAST:event_jmiObrisiAutoraActionPerformed

    private void jmiIzmenaAutoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzmenaAutoraActionPerformed

      FrmIzmenaAutora forma=new FrmIzmenaAutora(this, true);
        forma.setVisible(true);

      // FrmIzmenaAutora forma=new FrmIzmenaAutora(this, true);
        //forma.setVisible(true);
        
    }//GEN-LAST:event_jmiIzmenaAutoraActionPerformed

    private void jmiUnosAutoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosAutoraActionPerformed
        FUnosAutora forma=new FUnosAutora(this, true);
        forma.setVisible(true);
    }//GEN-LAST:event_jmiUnosAutoraActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FObrisiKlijenta forma=new FObrisiKlijenta(this, true);
        forma.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmiIzmenaDelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzmenaDelaActionPerformed
        FrmIzmenaDela forma=new FrmIzmenaDela(this, true);
        forma.setVisible(true);
    }//GEN-LAST:event_jmiIzmenaDelaActionPerformed

    private void jmiUnosDelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosDelaActionPerformed
        FormaUnosDela forma=new FormaUnosDela(this, true);
        forma.setVisible(true);
    }//GEN-LAST:event_jmiUnosDelaActionPerformed

    private void jmiUnosNarudzbeniceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosNarudzbeniceActionPerformed
     FrmNarudzbenica forma=new FrmNarudzbenica(korisnik);
      forma.setVisible(true);
      //  FormaUnosNarudzbenice forma=new FormaUnosNarudzbenice(this, true,korisnik);
       // forma.setVisible(true);
    }//GEN-LAST:event_jmiUnosNarudzbeniceActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
       
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jmiObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiObrisiActionPerformed
        FormaObrisiDelo forma=new FormaObrisiDelo(this, true);
        forma.setVisible(true);
    }//GEN-LAST:event_jmiObrisiActionPerformed

    private void jmiObrisiNarudbenicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiObrisiNarudbenicuActionPerformed
        FrnObrisiNarudzbenicu forma=new FrnObrisiNarudzbenicu(this, true);
        forma.setVisible(true);
    }//GEN-LAST:event_jmiObrisiNarudbenicuActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jmiIzmenaAutora;
    private javax.swing.JMenuItem jmiIzmenaDela;
    private javax.swing.JMenuItem jmiIzmenaKlijenta;
    private javax.swing.JMenuItem jmiObrisi;
    private javax.swing.JMenuItem jmiObrisiAutora;
    private javax.swing.JMenuItem jmiObrisiNarudbenicu;
    private javax.swing.JMenuItem jmiUnosAutora;
    private javax.swing.JMenuItem jmiUnosDela;
    private javax.swing.JMenuItem jmiUnosKlijenta;
    private javax.swing.JMenuItem jmiUnosNarudzbenice;
    // End of variables declaration//GEN-END:variables

}
