/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.narudzbenica;

import domen.Narudzbenica;
import forme.narudzbenica.model.NarudzbenicaModelTabeleObrisi;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import konstante.Konstante;
import sesija.Sesija;
import transfer.KlijentTransferObjekat;
import transfer.ServerTransferObjekat;

/**
 *
 * @author miljan
 */
public class FrnObrisiNarudzbenicu extends javax.swing.JDialog {

    /**
     * Creates new form FrnObrisiNarudzbenicu
     */
    public FrnObrisiNarudzbenicu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediTabelu();
        srediCmb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblNarudzbenica = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        cmbNarudzbenica = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtblNarudzbenica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblNarudzbenica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtblNarudzbenicaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtblNarudzbenica);

        jButton1.setText("Obrisi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbNarudzbenica.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNarudzbenicaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(161, 161, 161)
                        .addComponent(cmbNarudzbenica, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cmbNarudzbenica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbNarudzbenicaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNarudzbenicaItemStateChanged
        jtblNarudzbenica.setRowSelectionInterval(cmbNarudzbenica.getSelectedIndex(), cmbNarudzbenica.getSelectedIndex());
    }//GEN-LAST:event_cmbNarudzbenicaItemStateChanged

    private void jtblNarudzbenicaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblNarudzbenicaMousePressed
        cmbNarudzbenica.setSelectedIndex(jtblNarudzbenica.getSelectedRow());
    }//GEN-LAST:event_jtblNarudzbenicaMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // Narudzbenica narudzbenica=(Narudzbenica) cmbNarudzbenica.getSelectedItem();
        
        int indeks=jtblNarudzbenica.getSelectedRow();
        int brojNarudzebenice=(int) jtblNarudzbenica.getValueAt(indeks,0);
        Narudzbenica narudzbenica=new Narudzbenica();
        narudzbenica.setBrojNarudzbenice(brojNarudzebenice);
                
        KlijentTransferObjekat kto=new KlijentTransferObjekat();
        kto.setPodaci(narudzbenica);
       kto.setOperacija(Konstante.Obrisi_Narudbenicu);
        try {
            ObjectOutputStream out =new ObjectOutputStream(Sesija.dajObjekat().getSoket().getOutputStream());
            out.writeObject(kto);
            
            ObjectInputStream in =new ObjectInputStream(Sesija.dajObjekat().getSoket().getInputStream());
            ServerTransferObjekat sto=(ServerTransferObjekat) in.readObject();
            JOptionPane.showMessageDialog(this, sto.getPodaci());
            NarudzbenicaModelTabeleObrisi nmto=(NarudzbenicaModelTabeleObrisi) jtblNarudzbenica.getModel();
            nmto.obrisiNarudzbenicu(jtblNarudzbenica.getSelectedRow());
        } catch (IOException ex) {
            Logger.getLogger(FrnObrisiNarudzbenicu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrnObrisiNarudzbenicu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrnObrisiNarudzbenicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrnObrisiNarudzbenicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrnObrisiNarudzbenicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrnObrisiNarudzbenicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrnObrisiNarudzbenicu dialog = new FrnObrisiNarudzbenicu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbNarudzbenica;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblNarudzbenica;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
       
        try {
             KlijentTransferObjekat kto=new KlijentTransferObjekat();
        kto.setOperacija(Konstante.Vrati_Narudzbenice);
            ObjectOutputStream out =new ObjectOutputStream(Sesija.dajObjekat().getSoket().getOutputStream());
            out.writeObject(kto);
            
            ObjectInputStream in=new ObjectInputStream(Sesija.dajObjekat().getSoket().getInputStream());
            ServerTransferObjekat sto=(ServerTransferObjekat) in.readObject();
            ArrayList<Narudzbenica> lista=(ArrayList<Narudzbenica>) sto.getPodaci();
            NarudzbenicaModelTabeleObrisi nmto=new NarudzbenicaModelTabeleObrisi(lista);
            jtblNarudzbenica.setModel(nmto);
            for (Narudzbenica narudzbenica : lista) {
                cmbNarudzbenica.addItem(narudzbenica);
            }
           
        } catch (IOException ex) {
            Logger.getLogger(FrnObrisiNarudzbenicu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrnObrisiNarudzbenicu.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }

    private void srediCmb() {
     // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
