/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.autor;

import domen.Autor;
import forme.autor.ki.KontrolerKiIzmeniAutora;
import forme.autor.ki.KontrolerKiVratiAutora;
import forme.autor.model.AutorModelTabele;
import forme.autor.model.AutorModelTabeleIzmena;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import konstante.Konstante;
import sesija.Sesija;
import transfer.KlijentTransferObjekat;
import transfer.ServerTransferObjekat;

/**
 *
 * @author miljan
 */
public class FrmIzmenaAutora extends javax.swing.JDialog {

    /**
     * Creates new form FrmIzmenaAutora
     */
    public FrmIzmenaAutora(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //srediFormu();
        //srediTabelu();
        jTable1.setRowSelectionInterval(0, 0);
        KontrolerKiVratiAutora.vratiAutore(jTable1, cmbAutori);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbAutori = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSifraAutora = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        txtJMBG = new javax.swing.JTextField();
        txtAdresa = new javax.swing.JTextField();
        btnIzmeni = new javax.swing.JButton();
        jtblAutori = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbAutori.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAutoriItemStateChanged(evt);
            }
        });

        jLabel1.setText("Sifra autora:");

        jLabel2.setText("Ime :");

        jLabel3.setText("Prezime:");

        jLabel4.setText("Telefon:");

        jLabel5.setText("JMBG:");

        jLabel6.setText("Adresa:");

        txtSifraAutora.setEditable(false);
        txtSifraAutora.setBackground(new java.awt.Color(204, 204, 204));

        txtAdresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdresaActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jtblAutori.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbAutori, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtSifraAutora, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                        .addComponent(txtIme)
                                        .addComponent(txtPrezime)
                                        .addComponent(txtTelefon)
                                        .addComponent(txtJMBG))
                                    .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jtblAutori, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(31, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtSifraAutora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jtblAutori, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeni)
                    .addComponent(cmbAutori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAdresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdresaActionPerformed

    private void cmbAutoriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAutoriItemStateChanged
       Autor autor =(Autor) cmbAutori.getSelectedItem();
       txtSifraAutora.setText(String.valueOf(autor.getSifraAutora()));
       txtIme.setText(autor.getImeAutora());
       txtPrezime.setText(autor.getPrezimeAutora());
       txtTelefon.setText(autor.getTelefon());
       txtAdresa.setText(autor.getAdresa());
       txtJMBG.setText(autor.getJmbg());
       
      jTable1.setRowSelectionInterval(cmbAutori.getSelectedIndex(), cmbAutori.getSelectedIndex());
    try{
        
     // cmbAutori.setSelect;
    }catch(Exception ex){
        
    }
     
    }//GEN-LAST:event_cmbAutoriItemStateChanged

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
       /*try{
        int sifra=Integer.parseInt(txtSifraAutora.getText());
        String ime =txtIme.getText();
        String prezime=txtPrezime.getText();
        String telefon=txtTelefon.getText();
        String jmbg=txtJMBG.getText();
        String adresa=txtAdresa.getText();
        
        Autor autor=new Autor();
        autor.setSifraAutora(sifra);
        autor.setImeAutora(ime);
        autor.setPrezimeAutora(prezime);
        autor.setTelefon(telefon);
        autor.setJmbg(jmbg);
        autor.setAdresa(adresa);
        
        //posalji podatke serveru
           ObjectOutputStream out=new ObjectOutputStream(Sesija.dajObjekat().getSoket().getOutputStream());
           KlijentTransferObjekat kto=new KlijentTransferObjekat();
           kto.setOperacija(Konstante.Izmeni_Autora);
           kto.setPodaci(autor);
           out.writeObject(kto);
           
           
           //primi podatke sa servera
           ObjectInputStream in=new ObjectInputStream(Sesija.dajObjekat().getSoket().getInputStream());
           ServerTransferObjekat sto=(ServerTransferObjekat) in.readObject();
           JOptionPane.showMessageDialog(this, sto.getPoruka());
       
        
           AutorModelTabeleIzmena amt=(AutorModelTabeleIzmena) jTable1.getModel();
           amt.izmeniRed(cmbAutori.getSelectedIndex(), autor);
       
    
        }catch(Exception ex){
        JOptionPane.showMessageDialog(this,"Greska pri izmeni autora");
        }    
        */
        KontrolerKiIzmeniAutora.izmeniAutora(txtSifraAutora, txtIme, txtPrezime, txtTelefon, txtJMBG, txtAdresa, jTable1, cmbAutori);
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      
      // AutorModelTabeleIzmena amt=(AutorModelTabeleIzmena) jTable1.getModel();
        //cmbAutori.setSelectedItem(amt.getListaAutora().get(jTable1.getSelectedRow()));
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        cmbAutori.setSelectedIndex(jTable1.getSelectedRow());
    }//GEN-LAST:event_jTable1MousePressed
    
       
       
    
           
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIzmenaAutora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIzmenaAutora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIzmenaAutora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIzmenaAutora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmIzmenaAutora dialog = new FrmIzmenaAutora(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JComboBox cmbAutori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane jtblAutori;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJMBG;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtSifraAutora;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
       try{
           //posalji podatke serveru
          // ObjectOutputStream out=new ObjectOutputStream(Sesija.dajObjekat().getSoket().getOutputStream());
          
           KlijentTransferObjekat kto=new KlijentTransferObjekat();
           kto.setOperacija(Konstante.Vrati_Autore);
           Sesija.dajObjekat().upisiKlijentTransferObjekat(kto);
           //out.writeObject(kto);
           
           
           //primi podakte od servera
           //ObjectInputStream in =new ObjectInputStream(Sesija.dajObjekat().getSoket().getInputStream());
           
           ServerTransferObjekat sto=Sesija.dajObjekat().vratiServerTransferObjekat();
           
        ArrayList<Autor> listaAutora=(ArrayList<Autor>) sto.getPodaci();
           for (Autor autor : listaAutora) {
               cmbAutori.addItem(autor);
           }
           
           
        
          
       }catch(Exception ex){
           JOptionPane.showMessageDialog(this, "doslo je do greske");
    }
}

    private void srediTabelu() {
        try{
             //posalji podatke serveru
           //ObjectOutputStream out=new ObjectOutputStream(Sesija.dajObjekat().getSoket().getOutputStream());
           
           KlijentTransferObjekat kto=new KlijentTransferObjekat();
           kto.setOperacija(Konstante.Vrati_Autore);
           Sesija.dajObjekat().upisiKlijentTransferObjekat(kto);
           //out.writeObject(kto);
           
           
           //primi podakte od servera
           //ObjectInputStream in =new ObjectInputStream(Sesija.dajObjekat().getSoket().getInputStream());
           
           ServerTransferObjekat sto=Sesija.dajObjekat().vratiServerTransferObjekat();
           
           ArrayList<Autor> listaAutora=(ArrayList<Autor>) sto.getPodaci();
           AutorModelTabeleIzmena amt=new AutorModelTabeleIzmena(listaAutora);
           jTable1.setModel(amt);
       
               
            }catch(Exception ex){
          
      }
  }
   
}