/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.klijent;

import domen.Klijent;
import forme.klijent.ki.KontrolerKiIzmeniKlijenta;
import forme.klijent.ki.KontrolerKiVratiKlijente;
import forme.klijent.model.KlijentModelTabeleIzmena;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import konstante.Konstante;
import sesija.Sesija;
import transfer.KlijentTransferObjekat;
import transfer.ServerTransferObjekat;

/**
 *
 * @author miljan
 */
public class FIzmenaKlijenta extends javax.swing.JDialog {

    /**
     * Creates new form FIzmenaKlijenta
     */
    public FIzmenaKlijenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //ucitajComboBox();
       //srediTabelu();
        KontrolerKiVratiKlijente.vratiKlijente(jtblKlijenti, cmbKlijenti);
        jtblKlijenti.setRowSelectionInterval(0, 0);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSifraKlijenta = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        txtJMBG = new javax.swing.JTextField();
        txtAdresa = new javax.swing.JTextField();
        cmbKlijenti = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblKlijenti = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Sifra Autora:");

        jLabel2.setText("Ime:");

        jLabel3.setText("Prezime:");

        jLabel4.setText("Telefon:");

        jLabel5.setText("JMBG:");

        jLabel6.setText("Adresa:");

        cmbKlijenti.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbKlijentiItemStateChanged(evt);
            }
        });

        jButton1.setText("Izmeni");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtblKlijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblKlijenti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtblKlijentiMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtblKlijenti);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(229, 229, 229)
                        .addComponent(cmbKlijenti, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSifraKlijenta)
                                .addComponent(txtIme)
                                .addComponent(txtPrezime)
                                .addComponent(txtTelefon)
                                .addComponent(txtJMBG)
                                .addComponent(txtAdresa, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSifraKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKlijenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbKlijentiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbKlijentiItemStateChanged
       Klijent klijent=(Klijent) cmbKlijenti.getSelectedItem();
        txtSifraKlijenta.setText(String.valueOf(klijent.getIdKlijenta()));
        txtIme.setText(klijent.getIme());
        txtPrezime.setText(klijent.getPrezime());
        txtTelefon.setText(klijent.getTelefon());
        txtJMBG.setText(klijent.getJMBG());
        txtAdresa.setText(klijent.getAdresa());
       
      jtblKlijenti.setRowSelectionInterval(cmbKlijenti.getSelectedIndex(), cmbKlijenti.getSelectedIndex());
        try{
            
          // cmbKlijenti.setSelectedIndex(jtblKlijenti.getSelectedRow());
        }catch( Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Dogodila se greska pri selektovanju reda", "Greska", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_cmbKlijentiItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       /* try{
        int sifraKlijenta=Integer.parseInt(txtSifraKlijenta.getText());
        String ime=txtIme.getText();
        String prezime=txtPrezime.getText();
        String telefon=txtTelefon.getText();
        String jmbg=txtJMBG.getText();
        String adresa=txtAdresa.getText();
        
        Klijent klijent=new Klijent();
        klijent.setIdKlijenta(sifraKlijenta);
        klijent.setIme(ime);
        klijent.setPrezime(prezime);
        klijent.setTelefon(telefon);
        klijent.setJMBG(jmbg);
        klijent.setAdresa(adresa);
        
        //poslji podatke serveru
        ObjectOutputStream out=new ObjectOutputStream(Sesija.dajObjekat().getSoket().getOutputStream());
        KlijentTransferObjekat kto=new KlijentTransferObjekat();
        kto.setOperacija(Konstante.Izmeni_Klijenta);
        kto.setPodaci(klijent);
        out.writeObject(kto);
        
        //primi podatke od servera
        ObjectInputStream in =new ObjectInputStream(Sesija.dajObjekat().getSoket().getInputStream());
        ServerTransferObjekat sto=(ServerTransferObjekat) in.readObject();
        JOptionPane.showMessageDialog(this, sto.getPodaci());
        
        KlijentModelTabeleIzmena kmti=(KlijentModelTabeleIzmena) jtblKlijenti.getModel();
        kmti.izmeniRed(cmbKlijenti.getSelectedIndex(), klijent);
          
            
        }catch(Exception e){
            JOptionPane.showConfirmDialog(rootPane, "Doslo je od greske pri izmeni klijenta");
        }  
        */
        KontrolerKiIzmeniKlijenta.izmeniKlijenta(txtSifraKlijenta, txtIme, txtPrezime, txtTelefon, txtJMBG, txtAdresa, jtblKlijenti, cmbKlijenti);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtblKlijentiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblKlijentiMousePressed
       cmbKlijenti.setSelectedIndex(jtblKlijenti.getSelectedRow());
    }//GEN-LAST:event_jtblKlijentiMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FIzmenaKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FIzmenaKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FIzmenaKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FIzmenaKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FIzmenaKlijenta dialog = new FIzmenaKlijenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
     private void ucitajComboBox() {
        try{
            //posalji podatke serveru
            ObjectOutputStream out=new ObjectOutputStream(Sesija.dajObjekat().getSoket().getOutputStream());
            KlijentTransferObjekat kto =new KlijentTransferObjekat();
            kto.setOperacija(Konstante.Vrati_Klijenta);
            out.writeObject(kto);
                    
            //primi podatke od servera
            ObjectInputStream in=new ObjectInputStream(Sesija.dajObjekat().getSoket().getInputStream());
            ServerTransferObjekat sto=(ServerTransferObjekat) in.readObject();
            
            ArrayList<Klijent>listaKlijenata=(ArrayList<Klijent>) sto.getPodaci();
            for (Klijent klijent : listaKlijenata) {
                cmbKlijenti.addItem(klijent);
            }
        }  catch(Exception ex){
                
            }
        }

    private void srediTabelu() {
        try{
            //posalji podatke serveru 
            ObjectOutputStream out=new ObjectOutputStream(Sesija.dajObjekat().getSoket().getOutputStream());
            KlijentTransferObjekat kto=new KlijentTransferObjekat();
            kto.setOperacija(Konstante.Vrati_Klijenta);
            out.writeObject(kto);
            
            // primi podatke od servera
            ObjectInputStream in=new ObjectInputStream(Sesija.dajObjekat().getSoket().getInputStream());
            ServerTransferObjekat sto=(ServerTransferObjekat) in.readObject();
            
            
        ArrayList<Klijent>listaKlijenata=(ArrayList<Klijent>) sto.getPodaci();
        KlijentModelTabeleIzmena kmti=new KlijentModelTabeleIzmena(listaKlijenata);
        jtblKlijenti.setModel(kmti);
        }catch(Exception ex){
        
    }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbKlijenti;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblKlijenti;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJMBG;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtSifraKlijenta;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables

    


}
